- hosts: production-server
  become_user: root
  tasks:
  - name: copy petclinic
    copy:
      src: "/var/jenkins_home/workspace/assignment4/target/spring-petclinic-3.2.0-SNAPSHOT.jar"
      dest: "/home/spring-petclinic-3.2.0-SNAPSHOT.jar"
  - name: run petclinic
    shell: java -jar -Dserver.port=8100 /home/spring-petclinic-3.2.0-SNAPSHOT.jar
